In [1]:
from IPython.display import Audio
import numpy as np
import pandas as pd

signal = np.random.random(750)
Audio(signal, rate=250)

In [19]:
piano_path = "https://raw.githubusercontent.com/tipthederiver/Math-7243-2020/master/Labs/Lab%206/Piano%20Notes.csv"
notes = pd.read_csv(piano_path, encoding= 'unicode_escape')
notes

          Note  Frequency (Hz)  Wavelength (cm)  Key Position
0           C0           16.35          2109.89             1
1     C#0/Db0            17.32          1991.47             2
2           D0           18.35          1879.69             3
3     D#0/Eb0            19.45          1774.20             4
4           E0           20.60          1674.62             5
..         ...             ...              ...           ...
103         G8         6271.93             5.50           104
104   G#8/Ab8          6644.88             5.19           105
105         A8         7040.00             4.90           106
106   A#8/Bb8          7458.62             4.63           107
107         B8         7902.13             4.37           108

[108 rows x 4 columns]

In [3]:
notes[notes["Key Position"]==1]

  Note  Frequency (Hz)  Wavelength (cm)  Key Position
0   C0           16.35          2109.89             1

In [17]:
def gen_audio(song, notes, framerate=22050, L=.25):
    N = len(song)
    W = int(framerate*L)
    t = np.linspace(0,L,W)
    data = np.zeros(W*N)

    for i in range(N): 
        F = notes["Frequency (Hz)"].iloc[song[i]+1]
        data[W*i:W*(i+1)] = np.sin(2*np.pi*F*t)
        
    return data

In [5]:
song_0 = [65,65,65,65,72,72,70,70,69,69,67,67,65,65,65,65,72,72,72,72,74,74,74,74,74,74,74]
song_1 = [60,60,60,60,60,60,60,60,60,60,60,60,62,62,64,64,65,65,65,65,65,65,65,65,65,65,65]

In [7]:
data_0 = gen_audio(song_0, notes)
Audio(data_0,rate=22050)

In [8]:
data_0 = gen_audio(song_0, notes)
data_1 = gen_audio(song_1, notes)
Audio(data_0 + data_1,rate=22050)

In [1]:
import pandas as pd
import numpy as np
import os
import glob

base_path = 'jsb_chorales'
train_files = sorted(glob.glob(os.path.join(base_path, 'train', '*.csv')))
valid_files = sorted(glob.glob(os.path.join(base_path, 'valid', '*.csv')))
test_files = sorted(glob.glob(os.path.join(base_path, 'test', '*.csv')))

single_chorale = pd.read_csv(train_files[0])

chorale_array = single_chorale[['note0', 'note1', 'note2', 'note3']].values

In [2]:
def seq(chorale, seq_length=16):
    X = []
    y = []

    for i in range(len(chorale) - seq_length):
        X.append(chorale[i:i + seq_length])
        y.append(chorale[i + 1:i + seq_length + 1])

    return np.array(X), np.array(y)

seq_length = 16

X_single, y_single = seq(chorale_array, seq_length)

print(f"X shape: {X_single.shape}")
print(f"y shape: {y_single.shape}")

X shape: (176, 16, 4)
y shape: (176, 16, 4)

In [3]:
min_note = chorale_array.min()
max_note = chorale_array.max()

X_single_scaled = (X_single - min_note) / (max_note - min_note)
y_single_scaled = (y_single - min_note) / (max_note - min_note)

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

model_Bach = Sequential()
model_Bach.add(LSTM(64, input_shape=(seq_length, 4), return_sequences=True))
model_Bach.add(Dense(4, activation='sigmoid'))

model_Bach.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae'])

model_Bach.summary()

2025-11-09 12:32:27.461511: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2025-11-09 12:32:27.461570: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-11-09 12:32:27.461579: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2025-11-09 12:32:27.461622: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-11-09 12:32:27.461638: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/Users/sashwatdesai/Desktop/College/Masters/Northeastern University/SEMESTER WORK/Semester 3/Machine Learning 1 (MATH 7243)/Homework/Lab5/.venv/lib/python3.9/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 16, 64)         │        17,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 16, 4)          │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,924 (70.02 KB)

 Trainable params: 17,924 (70.02 KB)

 Non-trainable params: 0 (0.00 B)

In [5]:
history = model_Bach.fit(
    X_single_scaled,
    y_single_scaled,
    epochs=20,
    batch_size=32,
    verbose=1)

Epoch 1/20

2025-11-09 12:32:30.523206: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0683 - mae: 0.2274
Epoch 2/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0451 - mae: 0.1821
Epoch 3/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0275 - mae: 0.1359
Epoch 4/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0179 - mae: 0.1036
Epoch 5/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0166 - mae: 0.1014
Epoch 6/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0157 - mae: 0.0988
Epoch 7/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0144 - mae: 0.0938
Epoch 8/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0136 - mae: 0.0900
Epoch 9/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0128 - mae: 0.0871
Epoch 10/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0125 - mae: 0.0859
Epoch 11/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0121 - mae: 0.0842
Epoch 12/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0118 - mae: 0.0830
Epoch 13/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0113 - mae: 0.0817
Epoch 14/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0108 - mae: 0.0798
Epoch 15/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0107 - mae: 0.0795
Epoch 16/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0103 - mae: 0.0781
Epoch 17/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0100 - mae: 0.0767
Epoch 18/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0100 - mae: 0.0777
Epoch 19/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0097 - mae: 0.0761
Epoch 20/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0093 - mae: 0.0743

In [6]:
def seq_all(file_list, seq_length=16):
    X_full = []
    y_full= []
    
    for file_path in file_list:
        chorale_df = pd.read_csv(file_path)
        chorale_array = chorale_df[['note0', 'note1', 'note2', 'note3']].values
        
        X_temp, y_temp = seq(chorale_array, seq_length)
        if len(X_temp) > 0:
            X_full.extend(X_temp)
            y_full.extend(y_temp)
    
    return np.array(X_full), np.array(y_full)

X_train, y_train = seq_all(train_files, seq_length)
print(f"Training data: {X_train.shape}")

X_valid, y_valid = seq_all(valid_files, seq_length)
print(f"Validation data: {X_valid.shape}")

X_test, y_test = seq_all(test_files, seq_length)
print(f"Test data: {X_test.shape}")

all_notes = np.concatenate([X_train.flatten(), X_valid.flatten(), X_test.flatten()])
min_note = all_notes.min()
max_note = all_notes.max()

X_train_norm = (X_train - min_note) / (max_note - min_note)
y_train_norm = (y_train - min_note) / (max_note - min_note)

X_valid_norm = (X_valid - min_note) / (max_note - min_note)
y_valid_norm = (y_valid - min_note) / (max_note - min_note)

X_test_norm = (X_test - min_note) / (max_note - min_note)
y_test_norm = (y_test - min_note) / (max_note - min_note)

Training data: (51564, 16, 4)
Validation data: (17192, 16, 4)
Test data: (17668, 16, 4)

In [7]:
callbacks = [ModelCheckpoint('model_Bach.keras',
                            monitor='val_loss',
                            save_best_only=True,
                            verbose=1),
            EarlyStopping(monitor='val_loss',
                          patience=10,
                          restore_best_weights=True,
                          verbose=1)]

history_full = model_Bach.fit(
    X_train_norm, y_train_norm,
    validation_data=(X_valid_norm, y_valid_norm),
    epochs=50,
    batch_size=64,
    callbacks=callbacks,
    verbose=1)

Epoch 1/50
806/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0502
Epoch 1: val_loss improved from inf to 0.00354, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - loss: 0.0062 - mae: 0.0502 - val_loss: 0.0035 - val_mae: 0.0310
Epoch 2/50
799/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0017 - mae: 0.0268
Epoch 2: val_loss improved from 0.00354 to 0.00269, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 0.0017 - mae: 0.0268 - val_loss: 0.0027 - val_mae: 0.0252
Epoch 3/50
799/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0012 - mae: 0.0219
Epoch 3: val_loss improved from 0.00269 to 0.00228, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 0.0012 - mae: 0.0219 - val_loss: 0.0023 - val_mae: 0.0220
Epoch 4/50
800/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0010 - mae: 0.0192
Epoch 4: val_loss improved from 0.00228 to 0.00204, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 0.0010 - mae: 0.0192 - val_loss: 0.0020 - val_mae: 0.0197
Epoch 5/50
804/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2138e-04 - mae: 0.0174
Epoch 5: val_loss improved from 0.00204 to 0.00189, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 9.2117e-04 - mae: 0.0174 - val_loss: 0.0019 - val_mae: 0.0184
Epoch 6/50
804/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9922e-04 - mae: 0.0159
Epoch 6: val_loss improved from 0.00189 to 0.00179, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 7.9921e-04 - mae: 0.0159 - val_loss: 0.0018 - val_mae: 0.0171
Epoch 7/50
801/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8259e-04 - mae: 0.0149
Epoch 7: val_loss improved from 0.00179 to 0.00172, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 7.8236e-04 - mae: 0.0149 - val_loss: 0.0017 - val_mae: 0.0159
Epoch 8/50
804/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2653e-04 - mae: 0.0141
Epoch 8: val_loss improved from 0.00172 to 0.00168, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 7.2650e-04 - mae: 0.0141 - val_loss: 0.0017 - val_mae: 0.0152
Epoch 9/50
805/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7049e-04 - mae: 0.0133
Epoch 9: val_loss improved from 0.00168 to 0.00164, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.7054e-04 - mae: 0.0133 - val_loss: 0.0016 - val_mae: 0.0148
Epoch 10/50
801/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7171e-04 - mae: 0.0129
Epoch 10: val_loss improved from 0.00164 to 0.00160, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.7170e-04 - mae: 0.0129 - val_loss: 0.0016 - val_mae: 0.0139
Epoch 11/50
800/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.3690e-04 - mae: 0.0124
Epoch 11: val_loss did not improve from 0.00160
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.3708e-04 - mae: 0.0124 - val_loss: 0.0016 - val_mae: 0.0139
Epoch 12/50
799/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7409e-04 - mae: 0.0122
Epoch 12: val_loss improved from 0.00160 to 0.00159, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.7382e-04 - mae: 0.0122 - val_loss: 0.0016 - val_mae: 0.0138
Epoch 13/50
803/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.2625e-04 - mae: 0.0119
Epoch 13: val_loss improved from 0.00159 to 0.00157, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.2631e-04 - mae: 0.0119 - val_loss: 0.0016 - val_mae: 0.0129
Epoch 14/50
799/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.4190e-04 - mae: 0.0116
Epoch 14: val_loss improved from 0.00157 to 0.00156, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.4180e-04 - mae: 0.0116 - val_loss: 0.0016 - val_mae: 0.0128
Epoch 15/50
803/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.2544e-04 - mae: 0.0114
Epoch 15: val_loss did not improve from 0.00156
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.2545e-04 - mae: 0.0114 - val_loss: 0.0016 - val_mae: 0.0129
Epoch 16/50
806/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.2064e-04 - mae: 0.0113
Epoch 16: val_loss did not improve from 0.00156
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.2065e-04 - mae: 0.0113 - val_loss: 0.0016 - val_mae: 0.0129
Epoch 17/50
800/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.2935e-04 - mae: 0.0113
Epoch 17: val_loss improved from 0.00156 to 0.00154, saving model to model_Bach.keras
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.2927e-04 - mae: 0.0113 - val_loss: 0.0015 - val_mae: 0.0123
Epoch 18/50
800/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.2075e-04 - mae: 0.0111
Epoch 18: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.2072e-04 - mae: 0.0111 - val_loss: 0.0016 - val_mae: 0.0124
Epoch 19/50
805/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.5191e-04 - mae: 0.0112
Epoch 19: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.5182e-04 - mae: 0.0112 - val_loss: 0.0016 - val_mae: 0.0122
Epoch 20/50
806/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.3554e-04 - mae: 0.0110
Epoch 20: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.3552e-04 - mae: 0.0110 - val_loss: 0.0016 - val_mae: 0.0127
Epoch 21/50
800/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.9733e-04 - mae: 0.0109
Epoch 21: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 5.9747e-04 - mae: 0.0109 - val_loss: 0.0016 - val_mae: 0.0128
Epoch 22/50
806/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.3162e-04 - mae: 0.0109
Epoch 22: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.3159e-04 - mae: 0.0109 - val_loss: 0.0016 - val_mae: 0.0121
Epoch 23/50
805/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.0906e-04 - mae: 0.0109
Epoch 23: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.0907e-04 - mae: 0.0109 - val_loss: 0.0016 - val_mae: 0.0124
Epoch 24/50
804/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.1855e-04 - mae: 0.0110
Epoch 24: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.1852e-04 - mae: 0.0110 - val_loss: 0.0016 - val_mae: 0.0123
Epoch 25/50
801/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.1366e-04 - mae: 0.0109
Epoch 25: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 6.1361e-04 - mae: 0.0109 - val_loss: 0.0015 - val_mae: 0.0123
Epoch 26/50
806/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8586e-04 - mae: 0.0108
Epoch 26: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 5.8588e-04 - mae: 0.0108 - val_loss: 0.0016 - val_mae: 0.0123
Epoch 27/50
801/806 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8662e-04 - mae: 0.0107
Epoch 27: val_loss did not improve from 0.00154
806/806 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - loss: 5.8675e-04 - mae: 0.0107 - val_loss: 0.0016 - val_mae: 0.0136
Epoch 27: early stopping
Restoring model weights from the end of the best epoch: 17.

In [9]:
test_loss, test_mae = model_Bach.evaluate(X_test_norm, y_test_norm, verbose=0)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test MAE: {test_mae:.4f}")

Test Loss: 0.0011
Test MAE: 0.0117

In [24]:
def generate_chorale(model_Bach, X_test_norm):

    seed_idx = np.random.randint(0, len(X_test_norm))
    seed = X_test_norm[seed_idx]
    current_sequence = seed.copy()

    generated = []

    for _ in range(100):
        prediction_sequence = model_Bach.predict(
            current_sequence.reshape(1, seq_length, 4),
            verbose=0
        )

        next_timestep = prediction_sequence[0, -1, :]

        next_timestep = np.clip(next_timestep, 0, 1)

        generated.append(next_timestep)

        current_sequence = np.vstack([current_sequence[1:], next_timestep])

    generated = np.array(generated)  # Shape: (100, 4)

    full_chorale = np.vstack([seed, generated])

    full_chorale = full_chorale * (max_note - min_note) + min_note
    full_chorale = np.round(full_chorale).astype(int)

    pd.DataFrame(full_chorale, columns=['note0', 'note1', 'note2', 'note3']).to_csv('generated_chorale.csv', index=False)

    return full_chorale

chorale = generate_chorale(model_Bach, X_test_norm)

In [20]:
from IPython.display import Audio

generated_song_0 = pd.read_csv("generated_chorale.csv")

col_0 = generated_song_0["note0"]. values
col_1 = generated_song_0["note1"]. values
col_2 = generated_song_0["note2"]. values
col_3 = generated_song_0["note3"]. values

gen_data_0 = gen_audio(col_0, notes)
gen_data_1 = gen_audio(col_1, notes)
gen_data_2 = gen_audio(col_2, notes)
gen_data_3 = gen_audio(col_3, notes)
Audio(gen_data_0 + gen_data_1 + gen_data_2 + gen_data_3,rate=22050)